#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle
if [ -d "work" ]; then
  echo "› brew bundle --file work/Brewfile"
  brew bundle --file work/Brewfile
fi
if [ -d "home" ]; then
  echo "› brew bundle --file home/Brewfile"
  brew bundle --file home/Brewfile
fi

# find the installers and run them iteratively
for installer in $(find . -name install.sh)
do
  sh -c "${installer}"
done
